name: 1C_Task_CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build && cd build && cmake -DBUILD_TESTS=ON .. && make

      - name: Test
        run: |
          ./bin/Ctests